project:
  type: website

website:
  site-url: https://qiufei.github.io/web-slide-pandas3ed
  search: false
  # è®¾ç½®ç½‘ç«™å›¾æ ‡
  favicon: https://assets.qiufei.site/personal/profile.jpg
  # title: "è¯¾ä»¶"
  navbar:
    left:
      - text: "é¦–é¡µ"
        href: https://qiufei.github.io
    right:
      - text: è¯¾ä»¶
        href: https://qiufei.github.io/web-slide
      - about.qmd
  page-footer:
    left: ğŸ”‹[![](https://posit.co/wp-content/themes/Posit/assets/images/posit-logo-2024.svg){fig-alt="Posit" width=65px}](https://posit.co)
    center: 
      - text: "é‚±é£ &copy; 2025"
      - text: "æµ™ICPå¤‡ 2024072710å·-1"
        href: "https://beian.miit.gov.cn"
      - text: "æµ™å…¬ç½‘å®‰å¤‡ 33021202002511å·"
        href: "http://www.beian.gov.cn/portal/registerSystemInfo?recordcode=33021202002511"
    right:
      - icon: envelope-at-fill
        href: mailto:hfutqiufei@163.com
      # - text: â†
format:
  html:
    theme:
     light: journal
     dark: cyborg
    css: https://assets.qiufei.site/setup/styles.css

execute:
  freeze: auto



